### PR TITLE
Fixing build error with QT 5.4

### PR DESCRIPTION
**Pull request by develoken**
Make it work with downloaded version of QT 5.4.

### CODE REVIEW

**Comment by cameronwhite** [comment]
I think there needs to be a check for whether the `icu*.dll` files exist - the custom Qt build that I use for releases is compiled without ICU support so that those large dll's don't need to be included in the installer.

**Comment by develoken** [comment]
Updated it to copy icu*.dll files only if they exist.
I'm new to cmake so I am not sure if this is the correct way to do...
Let me know if this does not look good.

**Comment by cameronwhite** [comment]
It fails on my environment with being unable to find the `.pdb` files - for me they're under the lib folder, not the bin folder.

**Comment by develoken** [comment]
How do you want to fix it?
I could change it back to lib folder but then people who use downloaded QT package will have build error.
I think I could add some lines to copy QT*.dll, QT*.pdb and lib*.dll from lib to bin (or bin to lib). This will make both cases work. But I don't know if this is the cleanest way.
Let me know what you think.

**Comment by develoken** [comment]
Added a fix for copying pdb files.

**Comment by cameronwhite** [comment]
Thanks, looks good!

**Pull request merged**
