### PR TITLE
build: explicitly include std::optional in midiplayer.h

### PR DESCRIPTION
**Pull request by psyomn**
### Description of Change(s)

When trying to build this project on my machine, I got a compilation
error, complaining that the 'optional' type was not recognized.  I had
to explicitly include it in order to compile successfully.

Compilation was attempted with: gcc (GCC) 11.1.0

### Fixes Issue(s)
- N/A

### CODE REVIEW

**Comment by psyomn** [comment]
Not quite sure what's up with the mac build.  I'll take a look tomorrow!

**Comment by cameronwhite** [comment]
I'll have to look into the Mac build - it's not anything related to your change! The installer is now signed and notarized which requires some certificates / passwords that are registered as secrets in the main repo. Seems like they aren't accessible in PR builds (probably a good thing for security) so I'll need to adjust the build script a bit

**Comment by cameronwhite** [comment]
Is your fork fully up to date? I think 91506a36 fixed the same issue

**Comment by cameronwhite** [comment]
a00d7a7aa416ea4569f4819d59920dd7b4b1cc8c should hopefully fix the Mac issue!

I think this can be closed as it's already fixed now, thanks!

**Pull request closed without merging**
