### PR TITLE
Bend edits

### PR DESCRIPTION
**Pull request by PellTheTabber1**
I've added a new method to the PowerTabEditor class in app (powertabeditor.cpp/.h) called updateNoteDurationForBend.  This is called in the editBend method of the same class.

I then finished the else in midifile.cpp that had previously been a TODO, so that when the midi file plays, the note sounds the correct duration.

I did not put any error/sanity checking in, but at least I can play my bends with proper duration on midi playback now.  The note duration is still undoable as it was added with the Undo Manager.

The dialog does NOT currently have dotted duration bends, perhaps this can be added later.
I am coding on an Windows machine, but uploading from my Fatdog Linux, hence there may be text-formatting issues.  Not sure about this yet.  This is my first pull request.

I noticed a line where a variable pos is declared but never used.  I've removed this, however, I will not post the update as it's fairly trivial and will not affect the code's execution.  Sorry, I put that line in and did not need pos.

I have not agonized over whether this code could be put elsewhere such as in a constructor, and I have not range-checked it.  However, I need this code so bends sound the right amount.

I have also observed that with my new code that extends the duration of the note in the score itself, that in midifile.cpp, there is not as much need of an if-else if-else.  It can pretty much be an if and an else.  Perhaps I need to check this one in but assign an issue to get things cleaned up - Linux vs. Windows tabs and that generateGradualBend issue, and perhaps check the code by testing how each if/else and case sound.  It might be ok or almost ok.

### CODE REVIEW

**Comment by cameronwhite** [comment]
I'm traveling this week so I may not be able to do a proper review for a bit, but it looks like you've committed copies of the files? The diff probably shouldn't be several thousand lines

**Comment by PellTheTabber1** [comment]
True.  The diff should only be a line or two for a function declaration in powertabeditor.h, perhaps 10 - 15 lines in powertabeditor.cpp (for the function updateNoteDurationForBend), and about 3 lines (for an uncommented else) in midifile.cpp.  I edited the files on Windows, then emailed them to my Linux machine.  I'm just guessing this somehow caused a huge diff.  I'll have to run a diff.  Perhaps I need to open the files in a text editor.  I opened powertabeditor.cpp in Geany (my Fatdog development studio), and it does not seem to have any formatting problems.  Hmm?

**Comment by PellTheTabber1** [comment]
I wanted to change the if/else if/else, to simply an if/else anyway, and there is one variable pos, that I declared and never used.  Perhaps I can re-edit these files.  Should I close the pull request and re-submit a new one with hopefully, less diff, and with those minor changes?  I'm assuming that the content of what I did is acceptable, per the change in note duration, as it does solve the problem of the proper length.  In the meantime, if there are any issues, I'll be available to work on them.  I realize there seems to be a slight problem working on a different machine than the upload.  Perhaps I need to solve that (assuming that's what the problem is)?

**Comment by PellTheTabber1** [comment]
I have now found the Compare command on the upper right.  When I run it, I DO see that the file powertabeditor.cpp might have an issue - it said too many diffs or something - too large.  Hmm?  I'll look into it.

**Comment by PellTheTabber1** [comment]
One other issue with this task: I need to check my new code to make sure that it does not change the default note duration to be that of the bend's duration.  I believe I can see that it DOES change it in the method updateDuration.  So I need to save current and restore.  I'll do that in the editBend for now.  I have begun comparing the files.  I may try to add my new method at the end of the file.  If I move it there, the entire rest of the file except for the editBend method should be the same.  This might help.  I still don't yet have a true Compare running.  I only have the website version of Git right now - no clients installed yet.  But in the end, I would like the function to be right where it is, so I will only do this as a last resort.  I need to find an editor (perhaps over on my Windows machine in Visual Studio) that does a diff.  Or install something.

**Comment by PellTheTabber1** [comment]
I just shelled out to the Linux command line and ran the command:
diff powertabeditor.cpp.orig powertabeditor.cpp.myfile, and it simply lists the two changes I made, the new function, and the call of it in editBend, along with one other comment.  I will remove the comment.  So there were three differences found, totalling about 15 lines.

**Comment by PellTheTabber1** [comment]
Here is the output of the Linux diff command: diff powertabeditor.cpp.orig powertabeditor.cpp
922a923,935
> void PowerTabEditor::updateNoteDurationForBend(const ScoreLocation &location, const Note *note)
> {
>     const Bend &bend = note->getBend();
>     int bend_duration = bend.getDuration();
>     // Get beat value from time signature.
>     const Barline *barline = location.getBarline();
>     const TimeSignature &ts = barline->getTimeSignature();
>     int beatvalue = ts.getBeatValue();
>     int newduration = (int) beatvalue / bend_duration;
>     Position::DurationType newdt = (Position::DurationType) newduration;
>     updateNoteDuration(newdt);
> }
> 
1457a1471
> 			updateNoteDurationForBend(location, note);

**Comment by PellTheTabber1** [comment]
A woah - I now recall why I left the else in the original midifile.cpp generateGradualBend method.  I believe I had originally put the duration of the bend or something.  We need to distinguish the note duration when notes are LONGER than the bend.  So I may need to leave the note in if it's longer (no big deal, this can easily be changed).  And I may need that else so that I can put in the bend's duration.  My fear is that if the note is longer than the bend, that the bend will play through the entire note.  This is NOT wanted.  This shouldn't be hard to fix, so I won't put it in as an issue, but it's basically an issue right now, until I recode the else and test the new else behavior.

**Comment by PellTheTabber1** [comment]
So in the editBend method, I will first check that the note is long enough for the bend, if not, update the note's duration, if so, leave it alone.  I'll test this on windows.  Eventually, I would like to have a build for my Linux machine, so I'll start installing stuff for that.

**Comment by PellTheTabber1** [comment]
I have now tested this idea, I will update midifile.cpp with the newly coded else.  Then later I'll put in the powertabeditor.cpp < test change.  It's not as important as the midifile.cpp change so it can wait until I grab some lunch.

**Comment by PellTheTabber1** [comment]
So the newly updated midifile.cpp (which is now building) has bend.getDuration() * duration as the else's duration.  This seems to sound a lot better.  Let's hope.

**Comment by PellTheTabber1** [comment]
Cool, I checked out the behavior of bend if I increase the note's duration to values > than the bend's duration.  The code slices the bend up and makes it more gradual, but the pitch ends correctly.  So there's nothing to worry about.  This also suggests that it WOULD be ok to only increase the note's duration to the value of the bend if it's less.  I could possibly have a dialog pop up and remind the user that their bend is longer than the current note but I will leave my code in for updateNoteDurationForBend for now.  At least extended holds are working fine.

**Comment by PellTheTabber1** [comment]
When I posted Issue #225 (Bend and hold behavior), I had not yet checked that the function generateBends has both bend and note object refs passed in.  This will make it easy if we want to implement a check on the note's duration vs. the bend's, and if the note is greater, either turn the note on at that pitch or let it ring or whatever, those are details.  It shouldn't be difficult.

**Comment by PellTheTabber1** [comment]
One issue with updateNoteDuration is how to deal with the update.  We could use ties and simply fill in up to the amount needed by the bend.  But this might look strange for long bends - too many  little notes.  So I will need to test the value of newduration, and if it's less than 0 (eg. a 3 beat bend over a half-note = 2/3), take it's reciprocal, then integerize, fill in the appropriate number of notes, then take the remainder and use it to put in any smaller notes.  A little complicated, but doable.  I should look into this.

**Comment by PellTheTabber1** [comment]
Until I have this finished, I will need to test for the ratio < 1, and leave the note alone if so.

**Comment by PellTheTabber1** [comment]
Using ties is probably ok, as it is in the spirit of letting it ring anyway - this is the way I currently do my bends in Powertab, when I want it longer duration, but the bend is already up to pitch - a bend and hold.  If they want real long ones, perhaps they should just enter the notes themselves, until we can do better.  Seems reasonable.

**Comment by PellTheTabber1** [comment]
I am just getting back to this.  I will experiment with tweaking the pitch wheel with 0 bend - maybe that gives us a way of avoiding going through all the active players.  But I will still probably change the signature of the method so I can get note duration from position.  So this minor bug looks doable in a reasonable time.  For now, it's ok to use ties to accomplish the hold.

**Comment by PellTheTabber1** [comment]
The issue of Bend Duration over default or Current note duration + next x notes can be dealt with by inserting tied notes (programmatically) for a "hold".  The dialog might need a slight modification later to distinguish the bend duration from the hold.  The APIs within Powertab make this fairly simple to do.  So I view this as 3 stages.  We currently have the ability to use tied notes for the hold part of the bend (albeit with the misleading dialog info, no problem).  Then we change the dialog, and eventually, we can have a more sophisticated enunciation of how the notes will look.  Stage 1 we have now.  Stage 2 will simply be a slight advancement over Stage 1 by programmatically inserting - which will have it's own challenges for extreme cases of extending beyond barlines, etc...  Stage 3 will have a more complex presentation to the user and behind the scenes.  The pitch wheel CAN be used with 0 bend amount if we choose to do this (by giving the duration from some dialog), we'll see how this plays out.  It may not be necessary to use it, perhaps only in stage 3 (eg., if we give the user an option NOT to use tied notes, and instead, use a single note).  Then later, we can have a stage 4 and have dotted allowed, even from the dialog.  I don't think stage 4 is a high priority.

**Comment by PellTheTabber1** [comment]
Commiting Stage 2 implementation of Hold using tie notes per Issues 224/225.  Files affected: powertabeditor.cpp/.h, midifile.cpp

**Comment by PellTheTabber1** [comment]
Updating Stage 2 with fix of Normal Bend.  Normal Bend and Bend and Hold will both not use updateNoteDurationForBend.  Had briefly put it back in, but the code sounds the same between using ties and elongating the note.  So the code for normal bend and bend and hold are now more similar and each does it's thing ok.  A future issue might be to smooth out the bends more.  Low-priority item that can be done.  So I added a switch case and separated out a case to make it easier to deal with normal bends.  It's also possible to create a normal bend by simply using 0 for additional notes in a bend and hold, as before.  This may give slightly different behavior and this might be desirable.

**Comment by PellTheTabber1** [comment]
I tested the new pitch ranging code for Normal Bends on the attached file of Hotel California.ptb (zipped).  It sounds perfect.
[Eagles - Hotel California (power tab).zip](https://github.com/powertab/powertabeditor/files/495699/Eagles.-.Hotel.California.power.tab.zip)
Enjoy!

**Comment by cameronwhite** [comment]
Just getting back to looking at this ... the diff still seems rather large - it looks like perhaps line endings were changed?

**Comment by PellTheTabber1** [comment]
I believe this large diff happened once before due to a tabs vs. spaces issue.  The last time, I fixed a few lines, and then ran a diff and it was ok, perhaps I can do the same again.  I'll look at it.

**Comment by PellTheTabber1** [comment]
I just reformatted the files and directly uploaded them without looking at them in my Linux editor.  In future, I'll try to tweak the Linux editor to give the right end of line behavior.  These should look like windows files now.  Let's hope anyway.  Files are powertabeditor.cpp/.h, and midifile.cpp.  I assume these weren't changed in the master branch.

**Comment by PellTheTabber1** [comment]
Appveyor built ok.  Travis Cl failed when it could not find cmake.

**Comment by cameronwhite** [comment]
It looks like there were some changes on the Travis CI OSX environment - d979d832 fixes that.
If you look at https://github.com/powertab/powertabeditor/pull/224/files, the diff still looks incorrect

**Comment by PellTheTabber1** [comment]
Funny about the diff: I just opened the file midifile.cpp from the master branch, and copies a few lines to a buffer in my Linux editor.  The line endings are LF (which is Linux).  I then looked at my edit branch's copy of midifile.cpp, the one I've been adding stuff to (that seems to be causing the strange diff behavior), and it's line endings are CR-LF (which is Windows).  So all I have to do from now on is convert these to Linux.  My editor has a command that does that.  I just had never thought that you guys were maintaining things in Linux until now.  I'll update the files this evening.  Things should work normally from there on.  I assume all the files in Powertab's Github are LF-terminated, but I'll check a few more files to be sure.
Thanks for the fix of the Travis-CI.

**Comment by PellTheTabber1** [comment]
I committed 3 files whose line endings should be LF now (rather than CR-LF).
midifile.cpp, powertabeditor.h/.cpp

**Comment by cameronwhite** [comment]
I haven't looked at this in quite a while, apologies for that!

- Is the `updateNoteDurationForBend()` method still being used anywhere?
- There are still full copies of three files at the root of the repository, but the other files look like they have correct endings and diffs now

For a bend, the duration is (I think) the number of following notes to hold over, which isn't the same as the number of beats depending on the duration values of those notes. Was the intention just to insert placeholder notes that the user can adjust the duration for later?

**Comment by cameronwhite** [comment]
Closing old PR. I think this is addressed by ac6947149798219e9e46329e76cec9d6bff6a08f

**Pull request closed without merging**
